# -*- coding: utf-8 -*-
"""PROJECTS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17TP6GJho4xMymtyuM9iiClWCmLWYOC5b
"""

a= int(input("Enter any 3 non-similar digits number: "))  
b = 0    # initial value is 0. It will hold the reversed number  
def recur_reverse(a):  
    global b   # We can use it out of the function  
    if (a > 0):  
        Reminder = a % 10  
        b = (b * 10) + Reminder  
        recur_reverse(a // 10)  
    return b 
  
  
b= recur_reverse(a)  
print(b) 
print("****************************************")

if a>b:
  res=a-b
else:
  res=b-a
print(res)


f = 0    # initial value is 0. It will hold the reversed number  
def recur_reverse(res):  
    global f   # We can use it out of the function  
    if (res > 0):  
        Reminder = res % 10  
        f = (f * 10) + Reminder  
        recur_reverse(res// 10)  
    return f
f= recur_reverse(res) 
print(f) 
print("****************************************")
add=res+f
print(add)

"""PRACTICE PROJECT"""

def check(numbers):
  primenumber=[]
  for number in numbers:
    if number>1:
      for i in range(2,int(number/2)+1):
        if (number%i)==0: #if number is divisible by any number between 2 and number/2, it is nt prime
            print(number,"it is not prime")
            break
      else:
          print(number,"it is prime")
          primenumber.append(number)
    else:
        pass
  return primenumber
  
check([2,3,4,5,6,7,8,9,10,11])

# Python program to check if
# given number is prime or not

num = int(input("enter the number:"))

# If given number is greater than 1
if num > 1:

	# Iterate from 2 to n / 2
	for i in range(2, int(num/2)+1):

		# If num is divisible by any number between
		# 2 and n / 2, it is not prime
		if (num % i) == 0:
			print(num, "is not a prime number")
			break
	else:
		print(num, "is a prime number")

else:
	print(num, "is not a prime number")

#find perdentage and marks loss
class Student:
  Total=500 

  def __init__(self,marks):
    self.marks=marks
    print("initialized...")
  
  def findLoss(self):
    return (self.Total - self.marks)

  def findPercentage(self):
    return (self.marks/self.Total)*100

marks=int(input("marks scored : "))
a=Student(marks)

print("total marks :",a.Total)
print("Loss marks",a.findLoss()) #both findLoss & findPercntage are fuunctions we use paranthesis
print("Total percentage",a.findPercentage())